#!/usr/bin/php
<?php
/**
 * DDD
 * 
 * Области:
 * Коммандная строка
 * Файлы
 * XML, DOM, HTML
 * URI ссылки (RFC 3986)
 * Ошибки
 * 
 * Задачи:
 * Запрос на скачивание страницы
 * Парсер страницы
 * Подсчет искомых тегов
 * Сбор ссылок
 * Подготовка отчета
 * Создание файла отчета
 * Работа с ошибками
 * 
 * Сборщик в один скрипт по типу make) что бы прям unix way)
 * Тесты компонентов
 * 
 * chmod +x ./crawler
 */


if (php_sapi_name() !== 'cli') {
	exit;
}
set_time_limit(0);



abstract class ContentParserInterface
{
	function __construct(string $content)
	{
	}
	function report()
	{
	}
}

abstract class ReportFileBuilderInterface
{
	function __construct(array $table, string $output_file)
	{
	}
	function save()
	{
	}
}
